name: algolia-scraper

on:
  push:
    branches:
      - 2.1.0
  
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: check out code 🛎
        uses: actions/checkout@v2 
      - name: scrape the site 🧽
        env:
          ALGOLIA_APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
          ALGOLIA_WRITE_API_KEY: ${{ secrets.ALGOLIA_ADMIN_API_KEY }}
          ALGOLIA_SITE_URL: ${{ secrets.ALGOLIA_SITE_URL }}
          ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
          APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
          API_KEY: ${{ secrets.ALGOLIA_ADMIN_API_KEY }}
        run: |
          cd .algolia
          touch .env
          cat .env
          sudo chmod +x ./scraper.sh
          ./scraper.sh

      # 发送钉钉消息
      - name: build success
        if: ${{ success() }}
        uses: fifsky/dingtalk-action@master
        with:
          url: https://oapi.dingtalk.com/robot/send?access_token=${{ secrets.DING_TOKEN}}
          type: markdown
          at: ${{ secrets.DINGTALK_AT_USER }}
          content: |
            ### 💯👨‍💻 acp索引创建成功
            project: algolia index (${{ env.PRO_VERSION }}) 
            > Maven Build of [# ${{ env.PR_TITLE }}-${{ env.PRO_VERSION }}](${{ env.PR_URL }}) by ${{ env.PR_USER }} success
            > ^_^ from github action message
      - name: maven build failure
        if: ${{ failure() }}
        uses: fifsky/dingtalk-action@master
        with:
          url: https://oapi.dingtalk.com/robot/send?access_token=${{ secrets.DING_TOKEN}}
          type: markdown
          at: ${{ secrets.DINGTALK_AT_USER }}
          content: |
            ### 💤🤷‍♀️ acp索引创建失败
            project: algolia index (${{ env.PRO_VERSION }}) 
            > Maven Build of [# ${{ env.PR_TITLE }}-${{ env.PRO_VERSION }}](${{ env.PR_URL }}) by ${{ env.PR_USER }} failure
            > (⋟﹏⋞)   from github action message
