name: Algolia Upload Records
on:
  push:
    branches:
      - 2.1.0
jobs:
  algolia:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2 

      - name: Upload Records
        # 使用 Action
        uses: iChochy/Algolia-Upload-Records@main
        # 设置环境变量
        env:
          APPLICATION_ID: ${{secrets.ALGOLIA_APPLICATION_ID}}
          ADMIN_API_KEY: ${{secrets.ALGOLIA_ADMIN_API_KEY}}
          INDEX_NAME: ${{secrets.ALGOLIA_INDEX_NAME}}
          FILE_PATH: docs/algolia.json
